### PR TITLE
fix(rules): only report errors for prefer-to-have-value on valid DTL queries

### LINKED ISSUE #117: prefer-to-have-value having unintended effects
- `eslint-plugin-jest-dom` version: 3.5.0
- `node` version: 10.22.0
- `npm` version: 6.14.6

Relevant code or config

```javascript
const gen = someGeneratorFunction();
expect(gen.next().value).toEqual(someYieldedValue);
```

What you did: ^

What happened: `Prefer .toHaveValue() over other attribute checks`

Problem description:
The new rule `prefer-to-have-value` is causing unintended warnings when checking the `value` key on objects that are not DOM elements.

Suggested solution:
I'm not sure if there's a graceful solution that can allow for triggering warnings on `element.value` but not on `obj.value` (let me know if I'm wrong!). But I think a reasonable middle ground would be to allow a configuration option to only trigger a warning on `expect(element).toHaveAttribute('value', 'someValue')` so I don't have to individually turn off the rule everywhere I'm testing generators.

### PR DESCRIPTION
**Pull request by juzerzarif**
**What**:
`prefer-to-have-values` only reports an error for `expect(<something>.value).toEqual('foo')` pattern if `<something>` is the result of a valid DTL query. Only auto fix for `byRole('textbox')` and `byRole('dropdown')` queries, suggest fix for rest.

**Why**:
So `prefer-to-have-values` doesn't report an error when the value property of non DOM element objects are queried in an assertion. Auto fix update to only auto fix for recommended queries. 
Fixes #117

**How**:
Extracted existing logic for determining whether the value being queried in the assertion is a DOM element's value from the `prefer-in-document` rule.

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/rules/prefer-to-have-value.js [hunk 1]
```diff
@@ -21,62 +24,117 @@ export const meta = {
...
+      node
+    ) {
+      const { isValidQuery, isValidElement } = validateQueryNode(
+        node.callee.object.arguments[0].object
+      );
+      function fix(fixer) {
         return [
           fixer.removeRange([
-            node.callee.object.arguments[0].object.range[1],
+            node.callee.object.arguments[0].property.range[0] - 1,
```
Comment (benmonro) [inline src/rules/prefer-to-have-value.js:62]: what is the `-1` for?  generally hardcoded values in fixers can be problematic, unless you're inserting an arg (which i'd love to find a better way).

File: src/__tests__/lib/rules/prefer-to-have-value.js [hunk 2]
```diff
@@ -15,14 +15,34 @@ import * as rule from "../../../rules/prefer-to-have-value";
 // Tests
 //------------------------------------------------------------------------------
 
-const ruleTester = new RuleTester({ parserOptions: { ecmaVersion: 2015 } });
+const ruleTester = new RuleTester({ parserOptions: { ecmaVersion: 2017 } });
 
 const errors = [{ messageId: "use-to-have-value" }];
-ruleTester.run("prefer-empty", rule, {
```
Comment (benmonro) [inline src/__tests__/lib/rules/prefer-to-have-value.js:21]: wow thanks, that's what I get for copy pasta. :)

File: src/__tests__/lib/rules/prefer-to-have-value.js [hunk 3]
```diff
@@ -15,14 +15,34 @@ import * as rule from "../../../rules/prefer-to-have-value";
...
+ruleTester.run("prefer-to-have-value", rule, {
   valid: [
     `expect(element).toHaveValue('foo')`,
     `expect(element.value).toBeGreaterThan(2);`,
     `expect(element.value).toBeLessThan(2);`,
+
+    `const element = document.getElementById('asdfasf');
```
Comment (benmonro) [inline src/__tests__/lib/rules/prefer-to-have-value.js:27]: for now this is fine, but it would be nice to at some point support document queries as well as RTL. :)

File: src/utils.js [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+ * @param {Object} expression - An expression node
+ * @returns {Object} - A node
+ */
+export function getInnerNodeFrom(expression) {
+  return expression.type === "TSAsExpression"
+    ? getInnerNodeFrom(expression.expression)
+    : expression.type === "AwaitExpression"
+    ? getInnerNodeFrom(expression.argument)
+    : expression;
+}
```
Comment (benmonro) [inline src/utils.js:15]: this seems different than from what was in prefer-in-document: 

```
function getAssignmentFrom(expression) {
    return expression.type === "TSAsExpression"
      ? getAssignmentFrom(expression.expression)
      : expression.type === "AwaitExpression"
      ? getAssignmentFrom(expression.argument)
      : expression.callee
      ? expression.callee
      : expression;
  }
```

is expression.callee no longer needed?

File: src/utils.js [hunk 5]
```diff
@@ -0,0 +1,46 @@
+/**
```
Comment (benmonro) [inline src/utils.js:1]: i'm a bit of a stickler, but `utils` has always bothered me. :) Can we rename this to `assignment-ast.js` to denote that its purpose is for finding assignment values. :)

**Comment by benmonro** [comment]
Nice work @juzerzarif, a couple minor things then I think we're good to merge.

@all-contributors please add @juzerzarif for code, tests, bugs.

**Review by benmonro — CHANGES_REQUESTED** [review]
looking super!  just a couple minor things to tweak before merging.

File: src/rules/prefer-to-have-value.js (hunk 1 above)
Comment (juzerzarif) [reply src/rules/prefer-to-have-value.js:62]: If the object is wrapped in parentheses (like an inline await statement `expect((await screen.findByRole('textbox')).value)`), removing from the end of its range to the end of the property's range also gets rid of the closing wrapping parenthesis `expect((await screen.findByRole('textbox'))`. It does feel kinda icky to use magical numbers but I couldn't find another way to get around that than to just assume that the `.` preceding `value` will be just one over in the vast majority of cases. Definitely open to other suggestions though.

File: src/__tests__/lib/rules/prefer-to-have-value.js (hunk 3 above)
Comment (juzerzarif) [reply src/__tests__/lib/rules/prefer-to-have-value.js:27]: Yeah, my initial idea was to create a list of all the DOM api query functions but then it occurred to me that you can also get a reference to a dom element via a lot of other keys like `first/lastElementChild`, `children` etc. so I figured probably best to leave that to be implemented as its own piece

File: src/utils.js (hunk 4 above)
Comment (juzerzarif) [reply src/utils.js:15]: I had to make it return a slightly broader object because I needed access to the whole `CallExpression` in prefer-to-have-values to get access to its arguments as well as the callee. I've tweaked its consumption in prefer-in-document to maintain passivity here https://github.com/testing-library/eslint-plugin-jest-dom/pull/122/commits/e77f6b9f8dc3430743ccf2a5ae60224bb101e830#diff-6eab9c599f2637bd770a8d963e5c787cfd559888fe0c7b71fbab69d5d2bfff4bR160

File: src/utils.js (hunk 5 above)
Comment (juzerzarif) [reply src/utils.js]: Makes sense to me, renamed here https://github.com/testing-library/eslint-plugin-jest-dom/pull/122/commits/94aad94414dd435f14c4c40153dbcf39726e1b60

File: src/rules/prefer-to-have-value.js (hunk 1 above)
Comment (benmonro) [reply src/rules/prefer-to-have-value.js]: @juzerzarif, i did some digging and i think I found a winner!  you can use `context.getSourceCode().getTokenBefore(node)` or `getTokenAfter()`.  I discovered this by changing `.value` to be `.  value` which broke both the test for this use case as well as the ones i was using in to-have-class.  By switching to these functions they're now completely immune to spacing issues. :)  I hope you don't mind I just pushed it to your branch along w/ some other changes just extracting some variables out for readability.

**Review by benmonro — APPROVED** [review]
