### PR TITLE
fix(rules): Only report prefer-to-have-value errors on accepted queries

### LINKED ISSUE #131: don't report on getByRole("radio") for to-have-value
Relevant code or config

```javascript
      expect(screen.getAllByRole("radio")[0].value).toEqual("Any department");
```

What you did:
no error reported since you can't use `.toHaveValue` on radio buttons.

What happened:
error was reported.

Reproduction repository:

Problem description:

Suggested solution:

### PR DESCRIPTION
**Pull request by juzerzarif**
**What**:
Only report errors for prefer-to-have-values if the query node is one of the accepted queries for toHaveValue i.e. a `ByRole("textdown")` or a `ByRole("dropdown")` query. Fixes #131 

**Why**:
Avoid reporting errors unless we know that the assertion is definitely erroneous.

**How**:
Check to see that the query and the query argument is valid before reporting an error.

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/__tests__/lib/rules/prefer-to-have-value.js [hunk 1]
```diff
@@ -20,6 +20,10 @@ const ruleTester = new RuleTester({ parserOptions: { ecmaVersion: 2020 } });
 const errors = [{ messageId: "use-to-have-value" }];
 ruleTester.run("prefer-to-have-value", rule, {
   valid: [
+    `expect(screen.getByRole("radio").value).toEqual("foo")`,
+    `expect(screen.queryAllByRole("checkbox").value).toStrictEqual("foo")`,
```
Comment (benmonro) [inline src/__tests__/lib/rules/prefer-to-have-value.js:24]:
```suggestion
    `expect(screen.queryAllByRole("checkbox")[0].value).toStrictEqual("foo")`,
```

File: src/__tests__/lib/rules/prefer-to-have-value.js [hunk 2]
```diff
@@ -34,6 +38,10 @@ ruleTester.run("prefer-to-have-value", rule, {
     `const element = { value: 'foo' };
     expect(element.value).toBe('foo');`,
 
+    `expect(screen.getByRole("radio").value).not.toEqual("foo")`,
+    `expect(screen.queryAllByRole("checkbox").value).not.toStrictEqual("foo")`,
```
Comment (benmonro) [inline src/__tests__/lib/rules/prefer-to-have-value.js:42]:
```suggestion
    `expect(screen.queryAllByRole("checkbox")[0].value).not.toStrictEqual("foo")`,
```

**Review by benmonro — APPROVED** [review]
